### ISSUE TITLE
Fix RSpec tests so that they run successfully under docker containers

### ISSUE THREAD

**Issue by juniorsysadmin** [puppet-community/puppet-nodejs#137]
The RSpec tests can't currently be run on TravisCI with `sudo: false` as sadly one of the provider tests fail when this is set. Given how slow tests now run on non-docker TravisCI instances, fixing this would without doubt result in an immediate 50% increase in general health and well-being for any PR contributor.

**Comment by igalic** [comment]
\o/

**Comment by juniorsysadmin** [comment]
For those playing at home, the culprit when invoked on TravisCI is:
`
Failures:

  1) Puppet::Type::Package::ProviderNpm when npm packages are installed globally should log and return no packages if JSON isn't output

     Failure/Error: expect(@provider.class.instances).to eq([])
     Mocha::ExpectationError:
       unexpected invocation: Puppet.debug('Warning: npm list --json exited with code 126')
       unsatisfied expectations:
       - expected exactly once, not yet invoked: Puppet.debug(regexp_matches(/npm list.*failure!/))
`

**Comment by juniorsysadmin** [comment]
A hack fix has been done in #156
