### ISSUE TITLE
release 1.0.0

### ISSUE THREAD

**Issue by igalic** [puppet-community/puppet-nodejs#142]
it's time.

**Comment by nibalizer** [comment]
Is there any reason to do a 1.x release instead of another 0.x release? Do we have any feedback from users stating that the api right now is any good?

**Comment by igalic** [comment]
because to *actually* use semver, we should have a tripplet.

**Comment by nibalizer** [comment]
:shrug: okay

**Comment by juniorsysadmin** [comment]
I..er pushed out 1.1.0. The travis.yml needs to be fixed up so that only one attempt is made to push the Forge - that's the reason for no green badge.

**Comment by igalic** [comment]
time to pull out this issue again, huh: https://github.com/puppet-community/plumbing/issues/3
