### ISSUE TITLE
Add a dependency for treydock/gpg

### ISSUE THREAD

**Issue by everestx** [puppet-community/puppet-nodejs#143]
On Redhat systems, the `nodejs::repo::nodesource::yum` class uses a custom `gpg_key` resource type.  By default, this module is not specified in the dependency list.  It appears to be a hard dependency for yum based package managers.

**Comment by igalic** [comment]
is that a ***hard*** dependency?

**Comment by juniorsysadmin** [comment]
This isn't hard dependency. In some upcoming pull requests I will get rid of this dependency entirely by using new parameters in yum_repo making Puppet 3.6.x the minimum Puppet version.

**Comment by juniorsysadmin** [comment]
Aside: gpg_key currently appears to be broken when using Facter 2 or above.

**Comment by jantman** [comment]
@igalic is there any documentation re: metadata.json and hard vs soft dependencies? I just spent some time trying to figure out why we were getting ``Invalid resource type gpg_key`` errors, and only discovered this dependency by looking at the source, and at the wayyyyyy bottom of the README.

I'd assumed that if a module was using metadata.json, that would contain all dependencies, period...

**Comment by juniorsysadmin** [comment]
@jantman http://docs.puppetlabs.com/guides/style_guide.html#dependencies . I wish there was a solution with dependency-sets depending on osfamily, but sadly there isn't at the moment...

**Comment by nibalizer** [comment]
We could agree to set up a hash of 'indirect dependencies' inside metadata.json. cc @ryanycoleman
