### ISSUE TITLE
Support non-default (i.e. 0.12) versions on RedHat

### ISSUE THREAD

**Issue by jantman** [puppet-community/puppet-nodejs#159]
Nodesource has 0.12 RPMs available for RedHat, but this module doesn't seem to support them. The RPMs are available at: https://rpm.nodesource.com/pub_0.12/el/7/x86_64/

However, the module has the /pup/ directory [hard-coded](https://github.com/puppet-community/puppet-nodejs/blob/master/manifests/repo/nodesource.pp#L53) which will always give 0.10. This is [supported](https://github.com/puppet-community/puppet-nodejs/blob/master/README.md#beginning-with-nodejs) on Debian. It should be supported on RedHat as well.

**Comment by jantman** [comment]
WIP in a branch of mine, will be testing shortly.

**Comment by tommymcgahee** [comment]
Any updates on your WIP branch, jantman? I pulled your commit down to my Puppet master but this happens whenever I make a catalog request from my agent: 

Notice: /Stage[main]/Nodejs::Repo::Nodesource::Yum/Yumrepo[nodesource]/baseurl: baseurl changed 'https://rpm.nodesource.com/node_0.12/el/6/$basearch' to 'https://rpm.nodesource.com/pub/el/6/$basearch'
Notice: /Stage[main]/Nodejs::Repo::Nodesource::Yum/Yumrepo[nodesource-source]/baseurl: baseurl changed 'https://rpm.nodesource.com/node_0.12/el/6/SRPMS' to 'https://rpm.nodesource.com/pub/el/6/SRPMS'
Notice: /Stage[main]/Nodejs::Install/Package[nodejs]/ensure: created
Notice: Finished catalog run in 17.69 seconds

**Comment by igalic** [comment]
@jantman ping

**Comment by tommymcgahee** [comment]
@igalic I ended up creating a custom module using this package's npm.rb and grabbing the rpm from nodesource and installing via yum.  Very rudimentary, but it got the job done.  You can see it here - https://github.com/tommymcgahee/puppet-and-ci-managed-dev-environments/tree/puppet-master-foreman/modules/custom_node_npm

**Comment by juniorsysadmin** [comment]
#174

**Comment by juniorsysadmin** [comment]
Fixed by #174
