### ISSUE TITLE
Possibly missing dependency on puppetlabs-apt

### ISSUE THREAD

**Issue by ffrank** [puppet-community/puppet-nodejs#172]
On a fresh puppet install, the following manifest will not compile,

```
class {
	'nodejs':
		repo_url_suffix        => 'node_0.12',
		legacy_debian_symlinks => true;
}
```

Error is

    Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::apt for node.example.net at /home/ff/.puppetlabs/etc/code/modules/nodejs/manifests/repo/nodesource/apt.pp:11:3 on node node.example.net

Puppet 4.2.3

**Comment by igalic** [comment]
it's weird that we hard-depend on
```json
 {"name":"treydock/gpg_key","version_requirement":">=0.0.3 <1.0.0"}
```
but not on apt…

**Comment by juniorsysadmin** [comment]
If it's just needed for one OS, the style guide defines that as a soft dependency that should be listed in the README (The soft dependencies should be made a lot clearer in the README though)

**Comment by ffrank** [comment]
Oh right. It wouldn't make sense to pull that to `yum` machines. Closing.
