### ISSUE TITLE
What needs to be done to make this puppet 4 ready?

### ISSUE THREAD

**Issue by pskrz** [puppet-community/puppet-nodejs#175]
If ready, update metadata.json

**Comment by juniorsysadmin** [comment]
The unit tests currently test against Puppet 4/Ruby 2.1.6 and some time ago I applied this module with Puppet 4 on an Ubuntu 14.04 agent (puppetserver-2.1.1/puppet-agent-1.2.1). What is the issue you're facing?

**Comment by pskrz** [comment]
I was looking at the dependencies in the metadata.json and puppet 4 support
wasn't explicit
https://github.com/puppet-community/puppet-nodejs/blob/master/metadata.json#L65

On Mon, Nov 16, 2015 at 6:51 AM, Ben S <notifications@github.com> wrote:

> The unit tests currently test against Puppet 4/Ruby 2.1.6 and some time
> ago I applied this module with Puppet 4 on an Ubuntu 14.04 agent
> (puppetserver-2.1.1/puppet-agent-1.2.1). What is the issue you're facing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puppet-community/puppet-nodejs/issues/175#issuecomment-157007219>
> .
>



-- 
Dennis Paskorz | Developer, EotY

Wall-to-Wall Studios, Inc.
1010 Western Avenue, Suite 302, Pittsburgh, PA 15233
T 412 232 0880 | F 412 232 0906
W www.walltowall.com

**Comment by igalic** [comment]
@pskrz would you like to provide a patch for that?

**Comment by pskrz** [comment]
@igalic I set up a patch to update the version requirement, but perhaps the travis builds shouldn't allow failure for "Ruby: 2.1.6  PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"  ":

![screen shot 2015-11-18 at 8 49 59 am](https://cloud.githubusercontent.com/assets/605522/11242725/83fbb2a0-8dd1-11e5-9ef8-c10dc1c4b836.png)

**Comment by igalic** [comment]
perhaps it's time to put this module under modulesync control…
