### ISSUE TITLE
EPEL nodejs conflicting with nodejs-compat-symlinks

### ISSUE THREAD

**Issue by andyshinn** [puppet-community/puppet-nodejs#33]
It looks like package `nodejs-compat-symlinks` from http://patches.fedorapeople.org/oldnode/ wants to create `/usr/bin/node` and `/usr/include/node` which appear to be provided by a new EPEL `nodejs` package (added in April?).

I wonder if the EPEL packages might be better to rely on for RHEL5/6 compatibility? I am using http://forge.puppetlabs.com/stahnma/epel on all of my nodes since it provides many RPMs I rely on.

**Comment by juniorsysadmin** [comment]
Using the EPEL package (with the right parameters) should now work. If not, feel free to raise a new issue.
