### ISSUE TITLE
node.js manifests/params.pp & manifests/init.pp should support Scientific Linux

### ISSUE THREAD

**Issue by stefanlasiewski** [puppet-community/puppet-nodejs#37]
I am using Scientific Linux 6.4, which is a derivative of Red Hat Enterprise Linux and is similar to CentOS. SL is used extensively at research labs and higher-education institutions.

I was attempting to install Puppet Labs Razor onto a Scientific Linux 6.4 box, and the install failed with the following error. I posted the error to the puppet-razor mailing-list, and they recommended that I file a bug here [1].

    root@sl6:~ # puppet apply /etc/puppet/modules/razor/tests/init.pp
    Class nodejs does not support Scientific at /etc/puppet/modules/nodejs/manifests/params.pp:55 on node sl6.example.gov

It appears that node.js does not support Scientific Linux:

    root@sl6:~ # puppet apply /etc/puppet/modules/nodejs/tests/init.pp
    Class nodejs does not support Scientific at /etc/puppet/modules/nodejs/manifests/params.pp:55 on node sl6.example.gov

Please update nodejs to support Scientific Linux.

[1] https://groups.google.com/forum/#!topic/puppet-razor/bJIz1Fs7r7k

**Comment by juniorsysadmin** [comment]
Scientific Linux *should* work, but I haven't tested and can only base this opinion on unscientific evidence.
