### ISSUE TITLE
nodejs/manifests/params.pp installs /etc/yum.repos.d/nodejs-stable.repo which doesn't work with Scientific Linux 6.4

### ISSUE THREAD

**Issue by stefanlasiewski** [puppet-community/puppet-nodejs#38]
nodejs/tests/init.pp fails on my Scientific Linux 6.4 boxes with the following error:

```
root@sl6:~ # puppet apply /etc/puppet/modules/nodejs/tests/init.pp
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install nodejs-compat-symlinks' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: nodejs-stable. Please verify its path and try again

Error: /Stage[main]/Nodejs/Package[nodejs]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install nodejs-compat-symlinks' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: nodejs-stable. Please verify its path and try again

Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install npm' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: nodejs-stable. Please verify its path and try again

Error: /Stage[main]/Nodejs/Package[npm]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install npm' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: nodejs-stable. Please verify its path and try again
```

This issue arises from the following code  in nodejs/manifests/params.pp:

      $baseurl  = 'http://patches.fedorapeople.org/oldnode/stable/el$releasever/$basearch/'

On RHEL & CentOS, $releasever will return a single digit like '6', and thus the repo above will point to something like http://patches.fedorapeople.org/oldnode/stable/el6/x86_64/ .

However, on Scientific Linux, $releasever is often something like 6x or 6.4:

```
root@sl6:~ # python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
Loaded plugins: fastestmirror, priorities
{'arch': 'ia32e',
 'basearch': 'x86_64',
 'releasever': '6.4',
 'uuid': 'a7d2547c-c95c-4577-88e8-eb0b18c89101'}
```

Therefore, the URL will turn out to be something like http://patches.fedorapeople.org/oldnode/stable/el6.4/x86_64/, which doesn't exist. 

For now, a workaround is to manually modify /etc/puppet/modules/nodejs/manifests/params.pp & replace $releasever with '6', but this only works for a limited number of cases.

I am still familiarizing myself with Puppet and I am unsure how to fix this. However, the commit to puppet-yum (see link [1]) might have a solution. He make use of the $yum::osver & $common::osver variables:

```
-        baseurl => 'http://yum.puppetlabs.com/el/$releasever/dependencies/$basearch',
+        baseurl => "http://yum.puppetlabs.com/el/$common::osver/dependencies/\$basearch", 
```

[1] https://github.com/example42/puppet-yum/commit/764ee1bae17ae1c63cecc0f72381a9e8809d24a4 .

**Comment by juniorsysadmin** [comment]
This module should now work without dramas using the EPEL package or the packages from NodeSource. If it doesn't, feel free to open a new issue.
