### ISSUE TITLE
"Could not update: Got nil value for ensure" on "ensure => latest"

### ISSUE THREAD

**Issue by lunaryorn** [puppet-community/puppet-nodejs#43]
With `ensure => latest` this provider fails with `Could not update: Got nil value for ensure`, if the package is already at the latest version.

The culprit is likely [this line](https://github.com/puppetlabs/puppetlabs-nodejs/blob/0e85b5e27829e2508ee2edb142d00a1b65e3d511/lib/puppet/provider/package/npm.rb#L48) which fails to set `@property_hash[:ensure]` to the actual version of the package.

**Comment by juniorsysadmin** [comment]
Is this happening with the latest git sources?

**Comment by lunaryorn** [comment]
@juniorsysadmin I don't know.  You're a little late to ask.  I don't even use Puppet anymore.
