### ISSUE TITLE
Nodejs version under ubuntu

### ISSUE THREAD

**Issue by piotrrepetowski** [puppet-community/puppet-nodejs#48]
Guys I have a question:

Is there a way to disable node.js-devel repo for Ubuntu? Now when I install nodejs through puppet with:

class { "nodejs":
  version     => "latest",
  manage_repo => true,
}

I get newest version of nodejs from node.js-devel but I want to use stable version.

I don't understand why you added both repositories.

Best regards.

**Comment by juniorsysadmin** [comment]
The most recent 0.10.x version should now be installed by default, but if you have sufficient bandages for cuts to your fingers you should also be able to install 0.12.x on Debian-based platforms with `repo_url_suffix => 'node_0.12'`.
