### ISSUE TITLE
EL packages are ancient and from unofficial repo

### ISSUE THREAD

**Issue by jantman** [puppet-community/puppet-nodejs#49]
The EL packages used here are from an unofficial, no-longer-maintained repo, and are of NodeJS 0.6.x - the current version is 0.10.20 and there's been considerable change (specifically feature additions and optimizations) since then.

I have EL6 NodeJS 0.9.5 packages that work, and if similar isn't in EPEL yet, I can try to get them there (I was working with a maintainer for a while...). On EL5, however, it doesn't appear that current NodeJS will build at all.

**Comment by juniorsysadmin** [comment]
EL packages should now be installed smoothly. If not, feel free to open a new issue.
