### ISSUE TITLE
Enforce that npm is installed with collectors before using it

### ISSUE THREAD

**Issue by carlossg** [puppet-community/puppet-nodejs#54]
A package with provider => npm may run before npm is installed and fail

Not sure if it is ok to add it in the module, but at least should be in the README

if $::operatingsystem != 'ubuntu' {
  Package['npm'] -> Package <| provider == npm |>
} else {
  Package['nodejs'] -> Package <| provider == npm |>
}

An nodejs::npm anchor would also simplify the rule above

Does it look reasonable?

**Comment by juniorsysadmin** [comment]
Should no longer be occurring. Note that we also use `require => Class['nodejs']` in the npm defined type.
