### ISSUE TITLE
NPN Packages Global install on centos

### ISSUE THREAD

**Issue by jacinto123** [puppet-community/puppet-nodejs#57]
I have copied a pasted the code from the readme file:

package { 'express':
  ensure   => present,
  provider => 'npm',
}

and I keep getting the following error:
Error: /Stage[main]//Package[express]: Provider npm is not functional on this host

It appears to install on the machine because when I get in I can do npm install or npm -v

I am using:
Node: 0.10.22
Npm: 1.3.14
Centos 6.4

Any ideas of whats going on? Am I missing something that is not in the readme?

**Comment by juniorsysadmin** [comment]
Whatever the problem was, it should no longer be occurring.
