### ISSUE TITLE
Support nodejs-legacy package for Debian

### ISSUE THREAD

**Issue by mkmcdonald** [puppet-community/puppet-nodejs#67]
I experienced a problem today when provisioning a Debian Wheezy VM. Node.js and NPM would both install, but the two modules I used with them, buster and sinon, did not. Invocations of either binary would yield an error. It seemed that both relied on the `node` binary being available, which is not the case with the `nodejs` package in Debian. However, when the Debian team decided to rename to package, it added an additional package. That package is `nodejs-legacy`\[0\]. The package provides both the `node` and `nodejs` binaries, thereby providing both options to modules and developers alike.

\[0\]: https://packages.debian.org/sid/nodejs-legacy

**Comment by juniorsysadmin** [comment]
Equivalent functionality (if not using NodeSource) can be done with the `
legacy_debian_symlinks => true` parameter
